CREATE TABLE `pi_stats` (
  `realtime` int(11) NOT NULL default '0',
  `uptime` int(11) default NULL,
  `users_total` int(11) default '0',
  `users_zone0` int(11) default '0',
  `users_zone1` int(11) default '0',
  `users_zone2` int(11) default '0',
  `users_zone3` int(11) default '0',
  `users_zone4` int(11) default '0',
  `upload_total` double default '0',
  `upload_zone0` double default '0',
  `upload_zone1` double default '0',
  `upload_zone2` double default '0',
  `upload_zone3` double default '0',
  `upload_zone4` double default '0',
  `share_total_gb` int(11) default '0',
  `freq_search_active` double default '0',
  `freq_search_passive` double default '0',
  `freq_user_login` double default '0',
  `freq_user_logout` double default '0',
  PRIMARY KEY  (`realtime`)
) TYPE=MyISAM;