CREATE TABLE `reglist` (
  `nick` varchar(30) NOT NULL default '',
  `class` int(2) default '1',
  `class_protect` int(2) default '0',
  `class_hidekick` int(2) default '0',
  `hide_kick` tinyint(1) default '0',
  `reg_date` int(11) default NULL,
  `reg_op` varchar(30) default NULL,
  `pwd_change` tinyint(1) default '1',
  `pwd_crypt` tinyint(1) default '0',
  `login_pwd` varchar(60) default NULL,
  `login_last` int(11) default '0',
  `logout_last` int(11) default '0',
  `login_cnt` int(11) default '0',
  `login_ip` varchar(16) default NULL,
  `error_last` int(11) default NULL,
  `error_cnt` int(11) default '0',
  `error_ip` varchar(16) default NULL,
  `enabled` tinyint(1) default '1',
  `email` varchar(60) default NULL,
  `note_op` text,
  `note_usr` text,
  PRIMARY KEY  (`nick`),
  KEY `login_index` (`login_last`),
  KEY `logout_index` (`logout_last`)
) TYPE=MyISAM;